// Code generated by protoc-gen-go.
// source: 2pc.proto
// DO NOT EDIT!

/*
Package twopc is a generated protocol buffer package.

It is generated from these files:
	2pc.proto

It has these top-level messages:
	Message
	EmptyMessage
	SetRequest
*/
package twopc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MessageType int32

const (
	MessageType_VoteRequest   MessageType = 0
	MessageType_VoteCommit    MessageType = 1
	MessageType_VoteAbort     MessageType = 2
	MessageType_GlobalCommit  MessageType = 3
	MessageType_GlobalAbort   MessageType = 4
	MessageType_GlobalRequest MessageType = 5
	MessageType_ACK           MessageType = 6
)

var MessageType_name = map[int32]string{
	0: "VoteRequest",
	1: "VoteCommit",
	2: "VoteAbort",
	3: "GlobalCommit",
	4: "GlobalAbort",
	5: "GlobalRequest",
	6: "ACK",
}
var MessageType_value = map[string]int32{
	"VoteRequest":   0,
	"VoteCommit":    1,
	"VoteAbort":     2,
	"GlobalCommit":  3,
	"GlobalAbort":   4,
	"GlobalRequest": 5,
	"ACK":           6,
}

func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}
func (MessageType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type RequestType int32

const (
	RequestType_Get RequestType = 0
	RequestType_Set RequestType = 1
)

var RequestType_name = map[int32]string{
	0: "Get",
	1: "Set",
}
var RequestType_value = map[string]int32{
	"Get": 0,
	"Set": 1,
}

func (x RequestType) String() string {
	return proto.EnumName(RequestType_name, int32(x))
}
func (RequestType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Message struct {
	ClientID    uint64      `protobuf:"varint,1,opt,name=ClientID" json:"ClientID,omitempty"`
	MessageType MessageType `protobuf:"varint,2,opt,name=messageType,enum=twopc.MessageType" json:"messageType,omitempty"`
	RequestID   uint64      `protobuf:"varint,3,opt,name=requestID" json:"requestID,omitempty"`
	// Substantial request
	RequestType RequestType `protobuf:"varint,4,opt,name=requestType,enum=twopc.RequestType" json:"requestType,omitempty"`
	Key         []byte      `protobuf:"bytes,5,opt,name=key,proto3" json:"key,omitempty"`
	Value       []byte      `protobuf:"bytes,6,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Message) GetClientID() uint64 {
	if m != nil {
		return m.ClientID
	}
	return 0
}

func (m *Message) GetMessageType() MessageType {
	if m != nil {
		return m.MessageType
	}
	return MessageType_VoteRequest
}

func (m *Message) GetRequestID() uint64 {
	if m != nil {
		return m.RequestID
	}
	return 0
}

func (m *Message) GetRequestType() RequestType {
	if m != nil {
		return m.RequestType
	}
	return RequestType_Get
}

func (m *Message) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Message) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type EmptyMessage struct {
}

func (m *EmptyMessage) Reset()                    { *m = EmptyMessage{} }
func (m *EmptyMessage) String() string            { return proto.CompactTextString(m) }
func (*EmptyMessage) ProtoMessage()               {}
func (*EmptyMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type SetRequest struct {
	RequestType RequestType `protobuf:"varint,1,opt,name=requestType,enum=twopc.RequestType" json:"requestType,omitempty"`
	Key         []byte      `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value       []byte      `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *SetRequest) Reset()                    { *m = SetRequest{} }
func (m *SetRequest) String() string            { return proto.CompactTextString(m) }
func (*SetRequest) ProtoMessage()               {}
func (*SetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SetRequest) GetRequestType() RequestType {
	if m != nil {
		return m.RequestType
	}
	return RequestType_Get
}

func (m *SetRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *SetRequest) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "twopc.Message")
	proto.RegisterType((*EmptyMessage)(nil), "twopc.EmptyMessage")
	proto.RegisterType((*SetRequest)(nil), "twopc.SetRequest")
	proto.RegisterEnum("twopc.MessageType", MessageType_name, MessageType_value)
	proto.RegisterEnum("twopc.RequestType", RequestType_name, RequestType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Cluster service

type ClusterClient interface {
	Connection(ctx context.Context, opts ...grpc.CallOption) (Cluster_ConnectionClient, error)
	Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*EmptyMessage, error)
}

type clusterClient struct {
	cc *grpc.ClientConn
}

func NewClusterClient(cc *grpc.ClientConn) ClusterClient {
	return &clusterClient{cc}
}

func (c *clusterClient) Connection(ctx context.Context, opts ...grpc.CallOption) (Cluster_ConnectionClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Cluster_serviceDesc.Streams[0], c.cc, "/twopc.Cluster/Connection", opts...)
	if err != nil {
		return nil, err
	}
	x := &clusterConnectionClient{stream}
	return x, nil
}

type Cluster_ConnectionClient interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ClientStream
}

type clusterConnectionClient struct {
	grpc.ClientStream
}

func (x *clusterConnectionClient) Send(m *Message) error {
	return x.ClientStream.SendMsg(m)
}

func (x *clusterConnectionClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *clusterClient) Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*EmptyMessage, error) {
	out := new(EmptyMessage)
	err := grpc.Invoke(ctx, "/twopc.Cluster/Set", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Cluster service

type ClusterServer interface {
	Connection(Cluster_ConnectionServer) error
	Set(context.Context, *SetRequest) (*EmptyMessage, error)
}

func RegisterClusterServer(s *grpc.Server, srv ClusterServer) {
	s.RegisterService(&_Cluster_serviceDesc, srv)
}

func _Cluster_Connection_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ClusterServer).Connection(&clusterConnectionServer{stream})
}

type Cluster_ConnectionServer interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ServerStream
}

type clusterConnectionServer struct {
	grpc.ServerStream
}

func (x *clusterConnectionServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func (x *clusterConnectionServer) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Cluster_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/twopc.Cluster/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServer).Set(ctx, req.(*SetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Cluster_serviceDesc = grpc.ServiceDesc{
	ServiceName: "twopc.Cluster",
	HandlerType: (*ClusterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Set",
			Handler:    _Cluster_Set_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connection",
			Handler:       _Cluster_Connection_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "2pc.proto",
}

func init() { proto.RegisterFile("2pc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 339 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x92, 0x41, 0x4b, 0xc3, 0x40,
	0x14, 0x84, 0xbb, 0x4d, 0xd3, 0xd8, 0xd7, 0x36, 0x6e, 0x9f, 0x1e, 0x42, 0x11, 0x2c, 0x39, 0x85,
	0x1e, 0xaa, 0x44, 0xff, 0x40, 0x89, 0x52, 0x44, 0xbc, 0xa4, 0xe2, 0xbd, 0x2d, 0x0f, 0xa9, 0x26,
	0xd9, 0x98, 0x6c, 0x95, 0x80, 0xff, 0xd3, 0xbf, 0x23, 0x9b, 0xac, 0x36, 0x29, 0x5e, 0xbc, 0x65,
	0xe6, 0x0d, 0xdf, 0xb0, 0x43, 0xa0, 0xe7, 0xa7, 0x9b, 0x59, 0x9a, 0x09, 0x29, 0xd0, 0x94, 0x1f,
	0x22, 0xdd, 0xb8, 0x5f, 0x0c, 0xac, 0x07, 0xca, 0xf3, 0xd5, 0x33, 0xe1, 0x18, 0x8e, 0x82, 0x68,
	0x4b, 0x89, 0xbc, 0xbb, 0x71, 0xd8, 0x84, 0x79, 0x9d, 0xf0, 0x57, 0xe3, 0x35, 0xf4, 0xe3, 0x2a,
	0xf6, 0x58, 0xa4, 0xe4, 0xb4, 0x27, 0xcc, 0xb3, 0x7d, 0x9c, 0x95, 0x90, 0x59, 0xed, 0x12, 0xd6,
	0x63, 0x78, 0x06, 0xbd, 0x8c, 0xde, 0x76, 0x94, 0x2b, 0xa4, 0x51, 0x22, 0xf7, 0x86, 0x62, 0x6a,
	0x51, 0x32, 0x3b, 0x0d, 0x66, 0xed, 0x12, 0xd6, 0x63, 0xc8, 0xc1, 0x78, 0xa5, 0xc2, 0x31, 0x27,
	0xcc, 0x1b, 0x84, 0xea, 0x13, 0x4f, 0xc1, 0x7c, 0x5f, 0x45, 0x3b, 0x72, 0xba, 0xa5, 0x57, 0x09,
	0xd7, 0x86, 0xc1, 0x6d, 0x9c, 0xca, 0x42, 0xbf, 0xce, 0x7d, 0x01, 0x58, 0x92, 0x0c, 0x2b, 0xd2,
	0x61, 0x37, 0xfb, 0x57, 0x77, 0xfb, 0x8f, 0x6e, 0xa3, 0xd6, 0x3d, 0xfd, 0x6c, 0xac, 0x85, 0xc7,
	0xd0, 0x7f, 0x12, 0x92, 0x74, 0x37, 0x6f, 0xa1, 0x0d, 0xa0, 0x8c, 0x40, 0xc4, 0xf1, 0x56, 0x72,
	0x86, 0x43, 0xe8, 0x29, 0x3d, 0x5f, 0x8b, 0x4c, 0xf2, 0x36, 0x72, 0x18, 0x2c, 0x22, 0xb1, 0x5e,
	0x45, 0x3a, 0x60, 0x28, 0x42, 0xe5, 0x54, 0x91, 0x0e, 0x8e, 0x60, 0x58, 0x19, 0x3f, 0x50, 0x13,
	0x2d, 0x30, 0xe6, 0xc1, 0x3d, 0xef, 0x4e, 0xcf, 0x1b, 0x6f, 0x53, 0xfe, 0x82, 0x54, 0xab, 0x05,
	0xc6, 0x92, 0x24, 0x67, 0x7e, 0x02, 0x56, 0x10, 0xed, 0x72, 0x49, 0x19, 0xfa, 0x00, 0x81, 0x48,
	0x12, 0xda, 0xc8, 0xad, 0x48, 0xd0, 0xd6, 0x03, 0xe8, 0xcd, 0xc6, 0x07, 0xda, 0x6d, 0x79, 0xec,
	0x92, 0xe1, 0x45, 0xc9, 0xc1, 0x91, 0x3e, 0xee, 0x57, 0x1d, 0x9f, 0x68, 0xab, 0x31, 0x7c, 0x6b,
	0xdd, 0x2d, 0x7f, 0xb9, 0xab, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0b, 0xd6, 0x49, 0xff, 0x7f,
	0x02, 0x00, 0x00,
}
